- name: Install Neofetch on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install neofetch
      ansible.builtin.apt:
        name: neofetch
        state: present
